version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: nuget
    directory: /plugin/VestRumble
    schedule:
      interval: monthly
