<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>VestRumble</AssemblyName>
    <RootNamespace>VestRumble</RootNamespace>
    <LangVersion>9</LangVersion>
    <Nullable>disable</Nullable>
    <DebugType>none</DebugType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="BepInEx.BaseLib" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.10.2" />
    <PackageReference Include="UnityEngine.Modules" Version="2018.4.36" IncludeAssets="compile" />
  </ItemGroup>
</Project>
