# fish completions for vestctl (bhaptics-linux)
complete -c vestctl -f
complete -c vestctl -n __fish_use_subcommand -a status -d "vest/audio/game status"
complete -c vestctl -n __fish_use_subcommand -a pulse -d "buzz the vest"
complete -c vestctl -n __fish_use_subcommand -a stop -d "stop all effects"
complete -c vestctl -n __fish_use_subcommand -a wake -d "reconnect a sleeping vest"
complete -c vestctl -n __fish_use_subcommand -a audio -d "audio mode on/off"
complete -c vestctl -n __fish_use_subcommand -a auto -d "auto per-game presets on/off"
complete -c vestctl -n __fish_use_subcommand -a pad -d "gamepad rumble mirror on/off"
complete -c vestctl -n __fish_use_subcommand -a feel -d "tune strength/minimum/smooth/punch"
complete -c vestctl -n __fish_use_subcommand -a game -d "arm haptics for games (on/off/toggle)"
complete -c vestctl -n __fish_use_subcommand -a preset -d "list or apply presets"
complete -c vestctl -n __fish_use_subcommand -a effect -d "list or play saved effects"
complete -c vestctl -n __fish_use_subcommand -a play -d "list or play .tact patterns"
complete -c vestctl -n __fish_use_subcommand -a import -d "import .tact / haptic manifests"
complete -c vestctl -n __fish_use_subcommand -a sources -d "list audio sources"
complete -c vestctl -n __fish_use_subcommand -a proton -d "prep a Proton prefix for SDK2 mods"
complete -c vestctl -n __fish_use_subcommand -a doctor -d "diagnose a game's mod setup"
complete -c vestctl -n "__fish_seen_subcommand_from audio auto pad" -a "on off"
complete -c vestctl -n "__fish_seen_subcommand_from game" -a "on off toggle"
complete -c vestctl -n "__fish_seen_subcommand_from feel" -l strength -x -d "master strength 25-200 %"
complete -c vestctl -n "__fish_seen_subcommand_from feel" -l floor -x -a "0 1 2 3 4 5 6" -d "minimum motor level"
complete -c vestctl -n "__fish_seen_subcommand_from feel" -l smooth -x -a "on off" -d "finer intensity steps"
complete -c vestctl -n "__fish_seen_subcommand_from feel" -l punch -x -a "on off" -d "kick when a motor starts"
complete -c vestctl -n "__fish_seen_subcommand_from feel" -l test -d "play the feel test"
